//MAINCATEGORY
export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"
export const GET_MAINCATEGORY = "GET_MAINCATEGORY"
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED"
export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY"
export const UPDATE_MAINCATEGORY_RED = "UPDATE_MAINCATEGORY_RED"
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_RED = "DELETE_MAINCATEGORY_RED"


//SUBCATEGORY
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const CREATE_SUBCATEGORY_RED = "CREATE_SUBCATEGORY_RED"
export const GET_SUBCATEGORY = "GET_SUBCATEGORY"
export const GET_SUBCATEGORY_RED = "GET_SUBCATEGORY_RED"
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY_RED = "UPDATE_SUBCATEGORY_RED"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"
export const DELETE_SUBCATEGORY_RED = "DELETE_SUBCATEGORY_RED"

//BRAND
export const CREATE_BRAND = "CREATE_BRAND"
export const CREATE_BRAND_RED = "CREATE_BRAND_RED"
export const GET_BRAND = "GET_BRAND"
export const GET_BRAND_RED = "GET_BRAND_RED"
export const UPDATE_BRAND = "UPDATE_BRAND"
export const UPDATE_BRAND_RED = "UPDATE_BRAND_RED"
export const DELETE_BRAND = "DELETE_BRAND"
export const DELETE_BRAND_RED = "DELETE_BRAND_RED"

//PRODUCT
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCT_RED = "CREATE_PRODUCT_RED"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_RED = "GET_PRODUCT_RED"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_RED = "UPDATE_PRODUCT_RED"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED"

//FEATURE
export const CREATE_FEATURE = "CREATE_FEATURE"
export const CREATE_FEATURE_RED = "CREATE_FEATURE_RED"
export const GET_FEATURE = "GET_FEATURE"
export const GET_FEATURE_RED = "GET_FEATURE_RED"
export const UPDATE_FEATURE = "UPDATE_FEATURE"
export const UPDATE_FEATURE_RED = "UPDATE_FEATURE_RED"
export const DELETE_FEATURE = "DELETE_FEATURE"
export const DELETE_FEATURE_RED = "DELETE_FEATURE_RED"

//FAQ
export const CREATE_FAQ = "CREATE_FAQ"
export const CREATE_FAQ_RED = "CREATE_FAQ_RED"
export const GET_FAQ = "GET_FAQ"
export const GET_FAQ_RED = "GET_FAQ_RED"
export const UPDATE_FAQ = "UPDATE_FAQ"
export const UPDATE_FAQ_RED = "UPDATE_FAQ_RED"
export const DELETE_FAQ = "DELETE_FAQ"
export const DELETE_FAQ_RED = "DELETE_FAQ_RED"

//SETTING
export const CREATE_SETTING = "CREATE_SETTING"
export const CREATE_SETTING_RED = "CREATE_SETTING_RED"
export const GET_SETTING = "GET_SETTING"
export const GET_SETTING_RED = "GET_SETTING_RED"
export const UPDATE_SETTING = "UPDATE_SETTING"
export const UPDATE_SETTING_RED = "UPDATE_SETTING_RED"
export const DELETE_SETTING = "DELETE_SETTING"
export const DELETE_SETTING_RED = "DELETE_SETTING_RED"